name: Ejecucion de comandos de Linux

on:
  push:
    branches:
      - main
      
jobs:
  Comandos-basicos:
    runs-on: ubuntu-latest
    steps:
    
      - name: Step 1 - Listado de directorios
        run: ls -la
        
       - name: Step 2 - Fecha y hora del sistema
         run: date
         
        - name: Step 3 - Espacio en disco
          run: df -h
